[workspace]
channels = ["conda-forge", "conda-forge/label/python_rc"]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
python = ">=3.11,<3.16"
pytest = ">=9,<10"
# these should match the root pixi.toml
geoarrow-pyarrow = ">=0.3.0,<0.4"
geopandas = ">=1.2.0,<2"
rich-click = ">=1.9.9,<2"
sedonadb = ">=0.4.1,<0.5"

[tasks]
test = "pytest ../tests"

[pypi-dependencies]
giso = { path = "..", editable = false }

[environments]
py311 = { features = ["py311"] }
py312 = { features = ["py312"] }
py313 = { features = ["py313"] }
py314 = { features = ["py314"] }
py315 = { features = ["py315"] }

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

[feature.py314.dependencies]
python = "3.14.*"

[feature.py315.dependencies]
python = "3.15.*"
