[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
geoarrow-pyarrow = ">=0.3.0,<0.4"
geopandas = ">=1.2.0,<2"
rich-click = ">=1.9.9,<2"
sedonadb = ">=0.4.1,<0.5"

[pypi-dependencies]
giso = { path = ".", editable = true }

[environments]
default = { features = ["default"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "docs" }

[environments.dev]
features = ["dev", "docs"]
solve-group = "default"

[feature.dev.dependencies]
hatchling = ">=1.32.4,<2"
pandas-stubs = ">=3.0.5.260914,<4"
pixi-pycharm = ">=0.0.12,<0.0.13"
pytest = ">=9.1.1,<10"
pytest-cov = ">=7.1.0,<8"
ruff = ">=0.16.10,<0.17"
ty = ">=0.0.84,<0.0.85"
types-shapely = ">=2.1.0.20260402,<3"

[feature.dev.tasks]
build = "hatchling build"
checkall = { cmd = "echo 'All checks finished'", depends-on = ["coverage", "lint", "typecheck"]}
coverage = "pytest --cov=giso --cov-report=json:docs/pytest_coverage.json --cov-report=term-missing"
lint = "ruff check ./src ./tests && ruff format ./src ./tests"
test = "pytest ./tests"
typecheck = "ty check src/ tests/"

[feature.docs]
dependencies = { jupyter = ">=1.1.1,<2", myst-parser = ">=5.1.0,<6", nbsphinx = ">=0.9.8,<0.10", notebook = ">=7.6.3,<8", pydata-sphinx-theme = ">=0.22.0,<0.23", sphinx = ">=9.1.0,<10", sphinx-copybutton = ">=0.5.2,<0.6" }
tasks = { docs = "./docs/make html" }
target = { win-64 = { tasks = { docs = "./docs/make.bat html" } } }
