[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.10,<3.15"
geopandas = "*"
pyarrow = "*"
pyproj = "*"
shapely = "*"

[pypi-dependencies]
giso = { path = ".", editable = true }
apache-sedona = { version = ">=1.8.0", extras = ["db"]}

[feature.dev]
dependencies = { python = "3.14.*", black = "*", pandas-stubs = "*", pixi-pycharm = "*" }

[feature.coverage]
pypi-dependencies = { pytest = "*", slipcover = { git = "https://github.com/plasma-umass/slipcover", branch = "main" }}
tasks = { coverage = "slipcover --source src --json --pretty-print --out ./docs/pytest_coverage.json -m pytest" }

[feature.build]
dependencies = { hatchling = "*" }
tasks = { build = "hatchling build" }

[feature.docs]
# dependencies should match docs/requirements.txt
dependencies = { jupyter = "*", myst-parser = "*", nbsphinx = "*", notebook = "*", pydata-sphinx-theme = "*", sphinx = "*", sphinx-copybutton = "*" }
tasks = { docs = "./docs/make html" }
target = { win-64 = { tasks = { docs = "./docs/make.bat html" } } }

[feature.lint]
dependencies = { black = "*", ruff = "*" }
tasks = { lint = "black --check ./src ./tests && ruff check ./src ./tests", lint-format = "black ./src ./tests && ruff format ./src ./tests"}

[feature.test]
dependencies = { pytest = "*" }

[feature.py310]
dependencies = { python = "3.10.*" }
tasks = { test-py310 = "pytest" }

[feature.py311]
dependencies = { python = "3.11.*" }
tasks = { test-py311 = "pytest" }

[feature.py312]
dependencies = { python = "3.12.*" }
tasks = { test-py312 = "pytest" }

[feature.py313]
dependencies = { python = "3.13.*" }
tasks = { test-py313 = "pytest" }

[feature.py314]
dependencies = { python = "3.14.*" }
tasks = { test = "pytest", test-py314 = "pytest" }

[environments]
default = ["default"]
dev = ["dev", "build", "docs", "test"]
coverage = ["coverage", "test"]
build = ["build"]
docs = ["docs"]
lint = ["lint"]
test = ["test"]
py310 = ["py310", "test"]
py311 = ["py311", "test"]
py312 = ["py312", "test"]
py313 = ["py313", "test"]
py314 = ["py314", "test"]
