# https://github.com/marketplace/actions/setup-pixi
name: Update Test Coverage
on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#    paths: [ "src/**" ]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            docs/pytest_coverage.json
            pixi.lock
            pixi.toml
            pyproject.toml
            README.md
            src
            tests
          sparse-checkout-cone-mode: false
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.67.2
          cache: true
          environments: dev
          activate-environment: true
          locked: false
          frozen: true
      - name: Run coverage
        run: pixi run coverage
      - name: Push changes
        run: | 
          git config --local user.email "dev@corbelspatial.com"
          git config --local user.name "p-vdp"
          git add ./docs/pytest_coverage.json
          git commit -m "GitHub Action: Update Test Coverage"
          git push
