name: Pytest - Linux
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "src/**" ]
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        environment: [ py311, py312, py313, py314 ]
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github/pixi.lock
            .github/pixi.toml
            pyproject.toml
            README.md
            src
            tests
          sparse-checkout-cone-mode: false

      # https://github.com/marketplace/actions/setup-pixi
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.67.2
          cache: true
          environments: ${{ matrix.environment }}
          manifest-path: .github/pixi.toml
          activate-environment: true
          locked: false
          frozen: true
      - run: pytest tests
