name: Test Python Prerelease
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "src/**" ]
jobs:
  test-on-prerelease-python:
    runs-on: ubuntu-latest

    container: ghcr.io/corbel-spatial/here-be-dragons:next

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            pyproject.toml
            README.md
            src
            tests
          sparse-checkout-cone-mode: false

      - name: Install dependencies
        run: |
          uv pip install --system \
               https://github.com/geopandas/pyogrio.git
               https://github.com/pandas-dev/pandas.git
               https://github.com/geopandas/geopandas.git
          uv pip install --system maturin[patchelf] pytest
          uv venv --system-site-packages

      - name: Build sources
        run: |
          source .venv/bin/activate
          git clone --depth 1 https://github.com/apache/sedona-db.git
          cd sedona-db/python/sedonadb
          maturin develop --release
          deactivate
          uv pip install --system .

      - name: Run tests
        run: |
          cd /root/checkout
          uv pip install --system .
          pytest ./tests -vv -s
